### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by n0nuf2** [fmikker/syslogagent#1]
Hello. Where's the make file? Project file? How do you put this together and build it? Appears files are missing.

**Comment by fmikker** [comment]
Hi, 
this is everything I could salvage so I don't have any information or additional files for this project.
Please feel free to fork and add the missing build env. if you figure it out.

**Comment by dev681999** [comment]
Hi can please guide me to adding build files? I am unable to do it...

**Comment by fmikker** [comment]
> Hi can please guide me to adding build files? I am unable to do it...

See the previous answer. Ḯm sorry but this is all I have. :(
